# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore: # I don't want to mess up with tests and hooks
      - dependency-name: "pre-commit"
      - dependency-name: "yapf"
      - dependency-name: "prospector"
      - dependency-name: "pytest"
      - dependency-name: "pytest-cov"
  
