name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-pandas-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  -e .[pre-commit,testing]
          pip freeze

      - name: Run tests with pytest
        run: pytest -s # show output print
  build-pandas-2_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  -e .[pre-commit,testing]
          pip install pandas~=2.0.0
          pip freeze

      - name: Run tests with pytest
        run: pytest -s # show output print
  build-pandas-1_5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  -e .[pre-commit,testing]
          pip install pandas~=1.5.0
          pip freeze

      - name: Run tests with pytest
        run: pytest -s # show output print
