name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  -e .[pre-commit,testing]
          pip freeze

      - name: Run tests with pytest
        run: pytest --cov=./ --cov-report=xml


      # - name: Upload coverage report
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     name: pandas-chaining-ninja
      #     file: ./coverage.xml