name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build-pandas-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  -e .[testing]
          pip freeze
      - name: Show pandas version
        run: pip show pandas
      - name: Run tests with pytest
        run: pytest -s # show output print
        
  build-pandas-2_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  -e .[testing]
          pip install pandas~=2.0.0
          pip freeze
      - name: Show pandas version
        run: pip show pandas
      - name: Run tests with pytest
        run: pytest -s # show output print
        
  build-pandas-1_5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  -e .[testing]
          pip install pandas~=1.5.0
          pip freeze
      - name: Show pandas version
        run: pip show pandas
      - name: Run tests with pytest
        run: pytest -s # show output print

  build-pandas-1_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas~=1.4.0 ipython pytest pytest-cov
          pip freeze
      - name: Show pandas version
        run: pip show pandas
      - name: Run tests with pytest
        run: pytest -s # show output print

  build-pandas-1_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas~=1.3.0 ipython pytest pytest-cov
          pip freeze
      - name: Show pandas version
        run: pip show pandas
      - name: Run tests with pytest
        run: pytest -s # show output print

  build-pandas-1_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas~=1.2.0 ipython pytest pytest-cov
          pip freeze
      - name: Show pandas version
        run: pip show pandas
      - name: Run tests with pytest
        run: pytest -s # show output print

  build-pandas-1_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas~=1.1.0 ipython pytest pytest-cov
          pip freeze
      - name: Show pandas version
        run: pip show pandas
      - name: Run tests with pytest
        run: pytest -s # show output print